spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

  mustache:
    suffix: .html

server:
  port: 8080

logging:
  level:
    org.springframework.security: debug

app:
  mail-from: "sout1217@gmail.com"
