POST http://localhost:8080/api/v1/registrations
Content-Type: application/json

{
  "username": "root",
  "emailAddress": "sout1217@gmail.com",
  "password": "rootroot"
}

###

POST http://localhost:8080/api/v1/authentications
Content-Type: application/json

{
  "username": "root",
  "password": "rootroot"
}
